/* Local Safari bookmark importer + responsive layout + robust favicons/PWA. */
(function () {
  "use strict";
  const STORAGE_KEY = "myWebFavourites.safariBookmarks.v1";
  function getStored(){try{return localStorage.getItem(STORAGE_KEY)}catch{return null}}
  function parseBookmarks(html){
    const doc=new DOMParser().parseFromString(html,"text/html"),root=doc.querySelector('h3[id="BookmarksBar"]');
    if(!root)return null; const mainDL=root.nextElementSibling;if(!mainDL)return[]; const result=[];
    function readFolder(name,dl){const links=[];let node=dl.firstElementChild;while(node){if(node.tagName==="DT"){const h3=node.querySelector(":scope > H3"),childDL=node.querySelector(":scope > DL");if(h3&&childDL)readFolder(h3.textContent.trim(),childDL);const a=node.querySelector(":scope > A");if(a)links.push({title:a.textContent.trim(),url:a.href})}node=node.nextElementSibling}result.push({name,links})}
    let node=mainDL.firstElementChild;while(node){if(node.tagName==="DT"){const h3=node.querySelector(":scope > H3"),dl=node.querySelector(":scope > DL");if(h3&&dl)readFolder(h3.textContent.trim(),dl)}node=node.nextElementSibling}return result;
  }
  const stored=getStored();
  if(stored){const parsed=parseBookmarks(stored);if(parsed){const data={};parsed.forEach(f=>data[f.name]=f.links);window.__IMPORTED_BOOKMARKS__=data;window.__IMPORTED_FOLDER_ORDER__=parsed.map(f=>f.name)}}
  function faviconSources(url){try{const h=new URL(url).hostname.replace(/^www\./,"");return[`https://${h}/favicon.ico`,`https://www.google.com/s2/favicons?domain=${encodeURIComponent(h)}&sz=128`,`https://icons.duckduckgo.com/ip3/${h}.ico`,`https://favicon.im/${h}`,`https://favicon.yandex.net/favicon/${h}`]}catch{return[]}}
  function enhanceThumbnails(){document.querySelectorAll(".folder-icon img,.link-icon img").forEach(img=>{if(img.dataset.faviconEnhanced)return;let raw=img.getAttribute("src")||"";let u=raw;try{if(raw.includes("/favicon.ico")){const x=new URL(raw);u=x.origin}else if(raw.includes("google.com/s2/favicons")){const x=new URL(raw);u="https://"+x.searchParams.get("domain")}}catch{}const ss=faviconSources(u);if(!ss.length)return;let i=0;img.dataset.faviconEnhanced="1";img.src=ss[0];img.onerror=()=>{if(++i<ss.length)img.src=ss[i];else{img.style.display="none";const f=img.nextElementSibling;if(f)f.style.display=""}};img.onload=()=>img.classList.add("loaded")})}
  function installEnhancements(){
    if(document.getElementById("responsiveEnhancements"))return;
    const style=document.createElement("style");style.id="responsiveEnhancements";style.textContent=`
      html,body{width:100%;min-height:100%;}body{min-height:100dvh;overflow-x:hidden;}
      .home-view{flex:0 0 auto!important;height:auto!important;min-height:0!important;overflow:visible!important;width:100%;}
      .folders-grid{flex:0 0 auto!important;height:auto!important;min-height:0!important;overflow:visible!important;margin:0 auto!important;padding-bottom:10px!important;}
      @media(min-width:600px){body{justify-content:flex-start!important}.header{padding-top:16px!important;padding-bottom:4px!important}.top-bar{padding-top:4px!important;padding-bottom:8px!important}.folders-grid{grid-template-columns:repeat(8,minmax(0,1fr))!important;gap:14px 10px!important;max-width:920px!important}}
      @media(max-width:599px){html,body{min-height:100dvh!important;max-height:100dvh!important;overflow:hidden!important;overscroll-behavior:none!important}body{padding-left:10px!important;padding-right:10px!important;background-image:url('wallpaper-9x16.svg')!important;background-size:cover!important;background-position:center!important;background-repeat:no-repeat!important}.header{padding-top:max(14px,env(safe-area-inset-top))!important;padding-bottom:2px!important}.top-bar{padding:5px 2px 8px!important}.folders-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px 5px!important;padding:2px 0 6px!important}.folder-icon{width:64px!important;height:64px!important;border-radius:14px!important;padding:6px!important}.folder-label{font-size:10.5px!important;max-width:78px!important}}
      .home-view.hidden{display:none!important}.detail-view{display:none!important}.detail-view.active{display:flex!important;position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;max-width:none!important;margin:0!important;padding:max(12px,env(safe-area-inset-top)) 14px max(20px,env(safe-area-inset-bottom))!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior:contain!important;z-index:1000!important;background:transparent!important}
      body:has(.detail-view.active){overflow:hidden!important;position:fixed!important}body:has(.detail-view.active) .header,body:has(.detail-view.active) .top-bar{display:none!important}.detail-view.active .detail-header,.detail-view.active .links-grid{width:100%;max-width:920px;margin:0 auto}
      .detail-view .back-btn,.detail-view .theme-btn{width:48px!important;height:48px!important;min-width:48px!important;border-radius:50%!important;background:rgba(255,255,255,.18)!important;border:1px solid rgba(255,255,255,.32)!important;box-shadow:0 7px 22px rgba(0,0,0,.24),inset 0 1px 2px rgba(255,255,255,.3)!important;backdrop-filter:blur(20px) saturate(150%)!important;-webkit-backdrop-filter:blur(20px) saturate(150%)!important}.detail-view .back-btn{font-size:32px!important}.detail-view .theme-btn{font-size:24px!important}.detail-view .back-btn:active,.detail-view .theme-btn:active{transform:scale(.94);background:rgba(255,255,255,.28)!important}
    `;document.head.appendChild(style);
    const holder=document.createElement("div");holder.innerHTML='<link rel="icon" type="image/png" sizes="180x180" href="icon.png"><link rel="apple-touch-icon" sizes="180x180" href="icon.png"><link rel="manifest" href="manifest.webmanifest">';[...holder.children].forEach(n=>document.head.appendChild(n));
    if(!document.querySelector('meta[name="theme-color"]')){const m=document.createElement("meta");m.name="theme-color";m.content="#0b1930";document.head.appendChild(m)}
    if(!document.querySelector('meta[property="og:title"]')){const m=document.createElement("meta");m.setAttribute("property","og:title");m.content="My Safari Favourites";document.head.appendChild(m)}
    if(!document.querySelector('meta[property="og:image"]')){const m=document.createElement("meta");m.setAttribute("property","og:image");m.content=new URL("icon.png",location.href).href;document.head.appendChild(m)}
  }
  function addImportButton(){const top=document.querySelector(".top-bar,.top");if(!top||document.getElementById("localBookmarkImport"))return;const wrap=document.createElement("div");wrap.id="localBookmarkImport";wrap.style.cssText="display:flex;align-items:center;justify-content:center;margin-left:auto";const button=document.createElement("button");button.type="button";button.textContent=stored?"Change Bookmarks":"Import Bookmarks";button.className="refresh-btn";button.setAttribute("aria-label",button.textContent);const input=document.createElement("input");input.type="file";input.accept=".html,.htm,text/html";input.style.display="none";input.addEventListener("change",async()=>{const file=input.files&&input.files[0];if(!file)return;try{const html=await file.text();if(!parseBookmarks(html)){alert("This does not appear to be a Safari bookmark export.");input.value="";return}localStorage.setItem(STORAGE_KEY,html);location.reload()}catch(e){console.error(e);alert("The bookmark file could not be imported.")}});button.addEventListener("click",()=>input.click());wrap.append(button,input);top.appendChild(wrap)}
  function initialise(){installEnhancements();addImportButton();enhanceThumbnails();const mo=new MutationObserver(enhanceThumbnails);mo.observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initialise);else initialise();
})();
